version: '3'
services:
  web:
    image: django:latest
    volumes:
      - ./horizonvision:/app
    ports:
      - "8000:8000"
  frontend:
    image: node:latest
    volumes:
      - ./horizonvision:/app
    ports:
      - "8080:8080"
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
