version: '3.1'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ~Jing0910705
      MYSQL_DATABASE: hvdb
      MYSQL_USER: jing
      MYSQL_PASSWORD: Aa27378745
    ports:
      - "3306:3306"
