FROM python:3.8

WORKDIR /app

COPY backend/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ /app

EXPOSE 8000

CMD ["gunicorn", "-b", "0.0.0.0:8000", "HorizonVision.wsgi:application"]
