version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"

  # Database
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: horizonvision
      MYSQL_USER: horizonvision
      MYSQL_PASSWORD: horizonvision

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 

volumes:
  db_data: